export const demandF = {
  telegram: {
    objectId: "507f191e810c19729de860ea",
    status: "0",
    profile: {
      objectId: "507f191e810c19729de860ea",
      name: "@nothing",
    },
    overview: {
      review: {
        active: 0,
        normal: 0,
        low: 0,
        bot: 0,
      },
      activeReview: {
        active: "0",
        normal: "0",
        low: "0",
        bot: "0",
      },
      avg: {
        goodProfile: 0,
        avgActiveMember: 0,
        postimeFrans: "0",
        avgMess: 0,
      },
      activitiesOfTheWeek: {
        percentUser: {
          monday: 0,
          tuesday: 0,
          wednesday: 0,
          thursday: 0,
          friday: 0,
          saturday: 0,
          sunday: 0,
        },
      },
      hourOfOperation: {
        hour: null,
      },
      general: {
        numberOfSample: 0,
        numberOfConversation: 0,
        numberOfAdmin: 0,
      },
      ranking: null,
    },
    data: {
      data: null,
      status: "0",
    },
    result: null,
  },
  twitter: {
    objectId: "507f191e810c19729de860ea",
    status: "0",
    profile: {
      objectId: "507f191e810c19729de860ea",
      name: "@Scorpius",
      avatar: null,
      joinedData: null,
      tweet: 0,
      like: 0,
      follower: 0,
      following: 0,
    },
    overview: {
      hightQuality: 0,
      normalQuality: 0,
      lowQuality: 0,
      badQuality: 0,
      regularActivity: 0,
      profileAvatar: 0,
      followerSpread: 0,
      tweetRatio: 0,
      filledInBios: 0,
      bubblesSpread: 0,
      locationVerifycation: 0,
      followersWithURL: 0,
    },
    data: {
      data: null,
      status: "0",
    },
    result: null,
  },
  _id: "507f191e810c19729de860ea",
};
export const demand = {
  telegram: {
    objectId: "507f191e810c19729de860ea",
    status: "0",
    profile: {
      objectId: "507f191e810c19729de860ea",
      name: "@nothing",
    },
    overview: {
      review: {
        active: Math.floor(Math.random() * 100),
        normal: Math.floor(Math.random() * 100),
        low: Math.floor(Math.random() * 100),
        bot: Math.floor(Math.random() * 100),
      },
      activeReview: {
        active: Math.floor(Math.random() * 100),
        normal: Math.floor(Math.random() * 100),
        low: Math.floor(Math.random() * 100),
        bot: Math.floor(Math.random() * 100),
      },
      avg: {
        goodProfile: Math.floor(Math.random() * 100),
        avgActiveMember: Math.floor(Math.random() * 100),
        postimeFrans: Math.floor(Math.random() * 100),
        avgMess: Math.floor(Math.random() * 100),
      },
      activitiesOfTheWeek: {
        percentUser: {
          monday: Math.floor(Math.random() * 100),
          tuesday: Math.floor(Math.random() * 100),
          wednesday: Math.floor(Math.random() * 100),
          thursday: Math.floor(Math.random() * 100),
          friday: Math.floor(Math.random() * 100),
          saturday: Math.floor(Math.random() * 100),
          sunday: Math.floor(Math.random() * 100),
        },
      },
      hourOfOperation: {
        hour: null,
      },
      general: {
        numberOfSample: Math.floor(Math.random() * 100),
        numberOfConversation: Math.floor(Math.random() * 100),
        numberOfAdmin: Math.floor(Math.random() * 100),
      },
      ranking: null,
    },
    data: {
      data: {
        dataMembers: [],
        dataAdmins: [],
        dataMessages: [],
        status: "0",
      },
      status: "0",
    },
    result: null,
  },
  twitter: {
    objectId: "507f191e810c19729de860ea",
    status: "0",
    profile: {
      objectId: "507f191e810c19729de860ea",
      name: "@Scorpius",
      avatar: null,
      joinedData: null,
      tweet: Math.floor(Math.random() * 100),
      like: Math.floor(Math.random() * 100),
      follower: Math.floor(Math.random() * 100),
      following: Math.floor(Math.random() * 100),
    },
    overview: {
      hightQuality: Math.floor(Math.random() * 100),
      normalQuality: Math.floor(Math.random() * 100),
      lowQuality: Math.floor(Math.random() * 100),
      badQuality: Math.floor(Math.random() * 100),
      regularActivity: Math.floor(Math.random() * 100),
      profileAvatar: Math.floor(Math.random() * 100),
      followerSpread: Math.floor(Math.random() * 100),
      tweetRatio: Math.floor(Math.random() * 100),
      filledInBios: Math.floor(Math.random() * 100),
      bubblesSpread: Math.floor(Math.random() * 100),
      locationVerifycation: Math.floor(Math.random() * 100),
      followersWithURL: Math.floor(Math.random() * 100),
      lessTweets: Math.floor(Math.random() * 100),
    },
    data: {
      data: null,
      status: "0",
    },
    result: null,
  },
  _id: "507f191e810c19729de860ea",
};
