export const customers2 = [
  {
    title: "Binance",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
    value: 60,
    bg: "before:bg-info-500",
    barColor: "bg-info-500",
    active: false,
    number: 4,
  },
  {
    title: "Tether",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/825.png",
    value: 50,
    bg: "before:bg-warning-500",
    barColor: "bg-warning-500",
    active: false,
    number: 5,
  },
  {
    title: "USD Coin",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
    value: 40,
    bg: "before:bg-warning-400",
    barColor: "bg-warning-500",
    active: false,
    number: 6,
  },
  {
    title: "XRP",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
    value: 30,
    bg: "before:bg-warning-300",
    barColor: "bg-warning-500",
    active: false,
    number: 7,
  },
  {
    title: "Cadano",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png",
    value: 20,
    bg: "before:bg-warning-200",
    barColor: "bg-slate-400",
    active: false,
    number: 8,
  },
  {
    title: "Dogecoin",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png",
    value: 10,
    bg: "before:bg-info-500",
    barColor: "bg-info-500",
    active: false,
    number: 9,
  },
  {
    title: "Solana",
    img: "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png",
    value: 5,
    bg: "before:bg-warning-500",
    barColor: "bg-slate-400",
    active: false,
    number: 10,
  },
];
export const rowss = [
  {
    id: 1,
    age: 1,
    name: "BitScope",
    code: "BST",
    price: "$311.17",
    image: "https://i.imgur.com/gaIDZDP.png",
    tag: "#GaryGensler",
    value: 80,
    bg: "before:bg-white",
    barColor: "bg-white",
    number: 1,
    active: true,
  },
  {
    id: 2,
    age: 2,
    name: "Bitcoin",
    code: "BTC",
    price: "$26,785.68",
    image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
    tag: "#TruthGPT",
    value: 70,
    bg: "before:bg-warning-500",
    barColor: "bg-warning-500",
    number: 2,
  },

  {
    id: 3,
    age: 3,
    name: "Ethererum",
    code: "ETH",
    price: "$1,806.35",
    image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    tag: "#SEC",
    value: 65,
    bg: "before:bg-success-500",
    barColor: "bg-success-500",
    number: 3,
  },
];
export const rows = [
  {
    id: 1,
    age: 2,
    name: "Bitcoin",
    code: "BTC",
    price: "$26,785.68",
    image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
    tag: "#TruthGPT",
    value: 70,
    bg: "before:bg-warning-500",
    barColor: "bg-warning-500",
    number: 2,
  },
  {
    id: 2,
    age: 1,
    name: "BitScope",
    code: "BST",
    price: "$311.17",
    image: "https://i.imgur.com/gaIDZDP.png",
    tag: "#GaryGensler",
    value: 80,
    bg: "before:bg-info-500",
    barColor: "bg-info-500",
    number: 1,
    active: true,
  },
  {
    id: 3,
    age: 3,
    name: "Ethererum",
    code: "ETH",
    price: "$1,806.35",
    image: "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
    tag: "#SEC",
    value: 65,
    bg: "before:bg-success-500",
    barColor: "bg-success-500",
    number: 3,
  },
];
export const Trending = [
  {
    id: 1,
    tag: "#TruthGPT",
    price: "50 000",
  },
  {
    id: 2,
    tag: "#GaryGensler",
    price: "40 000",
  },
  {
    id: 3,
    tag: "#SEC",
    price: "30 000",
  },
];
export const post = [
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1590968738358079488/IY9Gx6Ok_400x400.jpg",
    name: "Elon Musk",
    status: "Just now",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-[#005AE2]",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/1651846384377577472/6JLb6sMF_x96.jpg",
    name: "CZ",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
  {
    image:
      "https://pbs.twimg.com/profile_images/977496875887558661/L86xyLF4_x96.jpg",
    name: "vitalik.eth",
    status: "April, 23",
    post: "Lorem ipsum dolor sit amet, Khánh Hoà consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore .....",
    retwit: "3",
    hurt: "7",
    ana: "166",
    link: "#",
    bg: "text-slate-500",
  },
];
